version: "2"

linters:
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    # default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - goimports

