apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: azure-cloud-node-manager
  namespace: openshift-cloud-controller-manager
  labels:
    k8s-app: azure-cloud-node-manager
    infrastructure.openshift.io/cloud-node-manager: {{ .cloudproviderName }}
    component: azure-cloud-node-manager
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: azure-cloud-node-manager
      infrastructure.openshift.io/cloud-node-manager: {{ .cloudproviderName }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        k8s-app: azure-cloud-node-manager
        infrastructure.openshift.io/cloud-node-manager: {{ .cloudproviderName }}
      annotations:
        cluster-autoscaler.kubernetes.io/daemonset-pod: "true"
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: cloud-node-manager
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          key: node-role.kubernetes.io/infra
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 120
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 120
      initContainers:
        - name: azure-inject-credentials
          image: {{ .images.Operator }}
          command:
            - /azure-config-credentials-injector
          args:
            - --cloud-config-file-path=/tmp/cloud-config/cloud.conf
            - --output-file-path=/tmp/merged-cloud-config/cloud.conf
          env:
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-cloud-credentials
                  key: azure_client_id
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-cloud-credentials
                  key: azure_client_secret
          volumeMounts:
            - name: config-accm
              mountPath: /tmp/cloud-config
              readOnly: true
            - name: cloud-config
              mountPath: /tmp/merged-cloud-config
      containers:
        - name: cloud-node-manager
          image: {{ .images.CloudNodeManager }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              set -o allexport
              if [[ -f /etc/kubernetes/apiserver-url.env ]]; then
                source /etc/kubernetes/apiserver-url.env
              fi
              exec /bin/azure-cloud-node-manager \
                --node-name=$(NODE_NAME) \
                --wait-routes=false \
                --use-instance-metadata=false \
                --cloud-config=$(CLOUD_CONFIG) \
                --v=6
          ports:
          - containerPort: 10263
            name: https
            protocol: TCP
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: AZURE_ENVIRONMENT_FILEPATH
              value: /etc/cloud-config-original/endpoints.conf
            - name: CLOUD_CONFIG
              value: /etc/cloud-config/cloud.conf
          volumeMounts:
            - name: host-etc-kube
              mountPath: /etc/kubernetes
              readOnly: true
            - name: config-accm
              mountPath: /etc/cloud-config-original
              readOnly: true
            - name: cloud-config
              mountPath: /etc/cloud-config
              readOnly: true
            - name: trusted-ca
              mountPath: /etc/pki/ca-trust/extracted/pem
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
      volumes:
        - name: host-etc-kube
          hostPath:
            path: /etc/kubernetes
            type: Directory
        - name: config-accm
          configMap:
            name: cloud-conf
            items:
              - key: cloud.conf
                path: cloud.conf
              - key: endpoints
                path: endpoints.conf
        - name: trusted-ca
          configMap:
            name: ccm-trusted-ca
            items:
              - key: ca-bundle.crt
                path: tls-ca-bundle.pem
        - name: cloud-config
          emptyDir: {}
