apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-aws-cloud-controller-manager
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: CloudCredential+CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  serviceAccountNames:
  - cloud-controller-manager
  secretRef:
    name: cloud-controller-manager-credentials
    namespace: openshift-cloud-controller-manager
  cloudTokenPath: /var/run/secrets/openshift/serviceaccount/token
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    stsIAMRoleARN: ""
    statementEntries:
    - effect: Allow
      action:
      # Node lifecycle
      - ec2:Describe*
      - ec2:CreateSecurityGroup
      - ec2:CreateTags
      - ec2:DeleteSecurityGroup
      - ec2:AuthorizeSecurityGroupIngress
      - ec2:RevokeSecurityGroupIngress
      - ec2:ModifyInstanceAttribute
      # Volume management
      - ec2:AttachVolume
      - ec2:CreateVolume
      - ec2:DeleteVolume
      - ec2:DetachVolume
      - ec2:ModifyVolume
      - kms:DescribeKey
      # Load balancer management (CLB)
      - elasticloadbalancing:AddTags
      - elasticloadbalancing:AttachLoadBalancerToSubnets
      - elasticloadbalancing:ApplySecurityGroupsToLoadBalancer
      - elasticloadbalancing:CreateLoadBalancer
      - elasticloadbalancing:CreateLoadBalancerPolicy
      - elasticloadbalancing:CreateLoadBalancerListeners
      - elasticloadbalancing:ConfigureHealthCheck
      - elasticloadbalancing:DeleteLoadBalancer
      - elasticloadbalancing:DeleteLoadBalancerListeners
      - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
      - elasticloadbalancing:Describe*
      - elasticloadbalancing:DetachLoadBalancerFromSubnets
      - elasticloadbalancing:ModifyLoadBalancerAttributes
      - elasticloadbalancing:RegisterInstancesWithLoadBalancer
      - elasticloadbalancing:SetLoadBalancerPoliciesForBackendServer
      - elasticloadbalancing:SetLoadBalancerPoliciesOfListener
      # Load balancer management (NLB/ALB)
      - elasticloadbalancing:CreateListener
      - elasticloadbalancing:CreateTargetGroup
      - elasticloadbalancing:DeleteListener
      - elasticloadbalancing:DeleteTargetGroup
      - elasticloadbalancing:DeregisterTargets
      - elasticloadbalancing:ModifyListener
      - elasticloadbalancing:ModifyTargetGroup
      - elasticloadbalancing:ModifyTargetGroupAttributes
      - elasticloadbalancing:RegisterTargets
      # BYO Security Group for NLB
      - elasticloadbalancing:SetSecurityGroups
      resource: "*"
