apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-ibm-cloud-controller-manager
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec:
  secretRef:
    name: ibm-cloud-credentials
    namespace: openshift-cloud-controller-manager
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: IBMCloudProviderSpec
    policies:
    - roles:
      - "crn:v1:bluemix:public:iam::::role:Editor"
      - "crn:v1:bluemix:public:iam::::role:Operator"
      - "crn:v1:bluemix:public:iam::::role:Viewer"
      attributes:
      - name: "serviceName"
        value: "is"
