apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: azure-cloud-node-manager
  namespace: openshift-cloud-controller-manager
  labels:
    k8s-app: azure-cloud-node-manager
    infrastructure.openshift.io/cloud-node-manager: {{ .cloudproviderName }}
    component: azure-cloud-node-manager
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: azure-cloud-node-manager
      infrastructure.openshift.io/cloud-node-manager: {{ .cloudproviderName }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        k8s-app: azure-cloud-node-manager
        infrastructure.openshift.io/cloud-node-manager: {{ .cloudproviderName }}
      annotations:
        cluster-autoscaler.kubernetes.io/daemonset-pod: "true"
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: cloud-node-manager
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          key: node-role.kubernetes.io/infra
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 120
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 120
      initContainers:
        # Merge /etc/kubernetes/cloud.conf (on the host) with secret "azure-cloud-credentials" into "merged-cloud-config" emptydir.
        - name: azure-inject-credentials
          image: {{ .images.CloudControllerManagerOperator }}
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              if [[ -f /etc/cloud-config/apiserver-url.env ]]; then
                cp /etc/cloud-config/apiserver-url.env /etc/merged-cloud-config/
              fi
              exec /azure-config-credentials-injector \
                --cloud-config-file-path=/etc/cloud-config/cloud.conf \
                --output-file-path=/etc/merged-cloud-config/cloud.conf \
                --disable-identity-extension-auth \
                --enable-azure-workload-identity=true
          env:
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-cloud-credentials
                  key: azure_client_id
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-cloud-credentials
                  key: azure_client_secret
                  optional: true
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-cloud-credentials
                  key: azure_tenant_id
                  optional: true
            - name: AZURE_FEDERATED_TOKEN_FILE
              valueFrom:
                secretKeyRef:
                  name: azure-cloud-credentials
                  key: azure_federated_token_file
                  optional: true
          volumeMounts:
            - name: host-etc-kube
              mountPath: /etc/cloud-config
              readOnly: true
            - name: merged-cloud-config
              mountPath: /etc/merged-cloud-config
      containers:
        - name: cloud-node-manager
          image: {{ .images.CloudNodeManager }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              set -o allexport
              if [[ -f /etc/kubernetes/apiserver-url.env ]]; then
                source /etc/kubernetes/apiserver-url.env
              fi
              exec /bin/azure-cloud-node-manager \
                --node-name=$(NODE_NAME) \
                --wait-routes=false \
                --enable-deprecated-beta-topology-labels
          ports:
          - containerPort: 10263
            name: https
            protocol: TCP
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: merged-cloud-config
              mountPath: /etc/kubernetes
              readOnly: true
            - name: trusted-ca
              mountPath: /etc/pki/ca-trust/extracted/pem
              readOnly: true
            - name: bound-sa-token
              mountPath: /var/run/secrets/openshift/serviceaccount
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
      volumes:
        - name: trusted-ca
          configMap:
            name: ccm-trusted-ca
            items:
              - key: ca-bundle.crt
                path: tls-ca-bundle.pem
        - name: host-etc-kube
          hostPath:
            path: /etc/kubernetes
            type: Directory
        - name: bound-sa-token
          projected:
            sources:
            - serviceAccountToken:
                path: token
                audience: openshift
        - name: merged-cloud-config
          emptydir:
